spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bevCarWashBot
    username: postgres
    password: 123456
  jpa:
#    hibernate:
#      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080

logging:
  level:
    ru.edu: info
  file:
    name: carService.log
    path: ./

service:
  title: CarWash service Api
  description: CarWash service description
  version: 1.0 BETA

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

# Эндпоинты входящих запросов
inEndpoint:
  carWashController: /api/v1/CarWash-service/carWash
  timeTableController: /api/v1/CarWash-service/timeTable

outEndpoint:
  userController:
    findById: http://localhost:8083/api/v1/admin-service/userInfo/findById/