spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/bevCarWashBot
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: always
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8087

logging:
  level:
    ru.edu: info
    org:
      springframework:
        web:
          client=DEBUG:
          client:
              RestTemplate=DEBUG:
      apache:
        http=DEBUG:
    httpclient:
      wire=DEBUG:
  file:
    name: carServiceBot.log
    path: ./

log4j:
  logger:
    httpclient:
      wire=DEBUG:

    org:
      springframework:
        web:
          client=DEBUG:


