spring:
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
server:
    port: 8083
